//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canton
    {
        public int provincia { get; set; }
        public int canton { get; set; }
        public string Nombre { get; set; }
    
        public virtual Provincia Provincia1 { get; set; }
    }
}
