//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companias()
        {
            this.Clientes = new HashSet<Clientes>();
            this.Facturas = new HashSet<Facturas>();
            this.Proveedores = new HashSet<Proveedores>();
            this.Sucursales = new HashSet<Sucursales>();
            this.Usuarios_Companias = new HashSet<Usuarios_Companias>();
        }
    
        public int id { get; set; }
        public int actividad_economica { get; set; }
        public string nombre { get; set; }
        public string tipo_identificacion { get; set; }
        public string identificacion { get; set; }
        public int tipo_compania { get; set; }
        public string telefono { get; set; }
        public string nombre_contacto { get; set; }
        public string apellido1_contacto { get; set; }
        public string apellido2_contacto { get; set; }
        public string email_contacto { get; set; }
        public int pais { get; set; }
        public string direccion { get; set; }
    
        public virtual Actividades_Economicas Actividades_Economicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual Tipo_Compania Tipo_Compania1 { get; set; }
        public virtual Identificacion_Tipos Identificacion_Tipos { get; set; }
        public virtual Consecutivos_Facturas Consecutivos_Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedores> Proveedores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursales> Sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Companias> Usuarios_Companias { get; set; }
    }
}
