//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDContext : DbContext
    {
        public BDContext()
            : base("name=BDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad_Economica> Actividad_Economica { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Categoria_Producto> Categoria_Producto { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Codigo_Impuesto> Codigo_Impuesto { get; set; }
        public virtual DbSet<Compania> Compania { get; set; }
        public virtual DbSet<Condicion_de_Venta> Condicion_de_Venta { get; set; }
        public virtual DbSet<Consecutivo_Factura> Consecutivo_Factura { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Facturas { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Forma_de_pago> Forma_de_pago { get; set; }
        public virtual DbSet<Identificacion_Tipo> Identificacion_Tipo { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Padron_Electoral> Padron_Electoral { get; set; }
        public virtual DbSet<Padron_Electoral_codelec> Padron_Electoral_codelec { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sucursale> Sucursale { get; set; }
        public virtual DbSet<Tipo_Comprobante> Tipo_Comprobante { get; set; }
        public virtual DbSet<Tipo_de_cambio> Tipo_de_cambio { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Compania> Usuario_Compania { get; set; }
        public virtual DbSet<Usuarios_Logins> Usuario_Login { get; set; }
    }
}
