//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDContext : DbContext
    {
        public BDContext()
            : base("name=BDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividad_Economica> Actividades_Economicas { get; set; }
        public virtual DbSet<Canton> Cantones { get; set; }
        public virtual DbSet<Categoria_Producto> Categorias_Productos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Codigo_Impuesto> Codigo_Impuestos { get; set; }
        public virtual DbSet<Compania> Companias { get; set; }
        public virtual DbSet<Condicion_de_Venta> Condiciones_de_Ventas { get; set; }
        public virtual DbSet<Consecutivo_Factura> Consecutivos_Facturas { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Facturas { get; set; }
        public virtual DbSet<Distrito> Distritos { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Forma_de_pago> Formas_de_pagos { get; set; }
        public virtual DbSet<Identificacion_Tipo> Identificacion_Tipos { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimientos { get; set; }
        public virtual DbSet<Padron_Electoral> Padron_Electoral { get; set; }
        public virtual DbSet<Padron_Electoral_codelec> Padron_Electoral_codelec { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Proveedor> Proveedores { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sucursale> Sucursales { get; set; }
        public virtual DbSet<Tipo_Comprobante> Tipo_Comprobantes { get; set; }
        public virtual DbSet<Tipo_de_cambio> Tipo_de_cambio { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedidas { get; set; }
        public virtual DbSet<User_Role> User_Roles { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuario_Compania> Usuarios_Companias { get; set; }
        public virtual DbSet<Usuario_Login> Usuarios_Logins { get; set; }
    }
}
