//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDContext : DbContext
    {
        public BDContext()
            : base("name=BDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Actividades_Economica> Actividades_Economica { get; set; }
        public virtual DbSet<Canton> Cantons { get; set; }
        public virtual DbSet<Categorias_Productos> Categorias_Productos { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Codigo_Impuestos> Codigo_Impuestos { get; set; }
        public virtual DbSet<Compania> Companias { get; set; }
        public virtual DbSet<Condiciones_de_Ventas> Condiciones_de_Ventas { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Distrito> Distritos { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<Formas_de_pagos> Formas_de_pagos { get; set; }
        public virtual DbSet<Identificacion_Tipos> Identificacion_Tipos { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimientos { get; set; }
        public virtual DbSet<Padron_Electoral> Padron_Electoral { get; set; }
        public virtual DbSet<Padron_Electoral_codelec> Padron_Electoral_codelec { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sucursal> Sucursals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Comprobantes> Tipo_Comprobantes { get; set; }
        public virtual DbSet<Tipo_de_cambio> Tipo_de_cambio { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedidas { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<Usuarios_Companias> Usuarios_Companias { get; set; }
        public virtual DbSet<Usuarios_Logins> Usuarios_Logins { get; set; }
        public virtual DbSet<Consecutivos_Facturas> Consecutivos_Facturas { get; set; }
    }
}
