//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventarios
    {
        public int id { get; set; }
        public int categoria { get; set; }
        public int proveedor { get; set; }
        public int cantidad { get; set; }
        public string descripcion { get; set; }
        public int minimo { get; set; }
        public int ventaMinima { get; set; }
        public int exento { get; set; }
        public int precio { get; set; }
    
        public virtual Categorias_Productos Categorias_Productos { get; set; }
        public virtual Proveedor Proveedores { get; set; }
    }
}
