//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Inventarios = new HashSet<Inventario>();
        }
    
        public int id { get; set; }
        public int id_compania { get; set; }
        public string nombre_comercial { get; set; }
        public string dni { get; set; }
        public int tipo_dni { get; set; }
        public int actividad_economica { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public int pais { get; set; }
        public int provincia { get; set; }
        public int canton { get; set; }
        public int distrito { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
    
        public virtual Compania Compania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventarios { get; set; }
        public virtual Compania Compania1 { get; set; }
    }
}
