//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Roles
    {
        public int id { get; set; }
        public int usuario { get; set; }
        public int role { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
