//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Facturas = new HashSet<Factura>();
            this.User_Roles = new HashSet<User_Roles>();
            this.Usuarios_Companias = new HashSet<Usuarios_Companias>();
            this.Usuarios_Logins = new HashSet<Usuarios_Login>();
        }
    
        public int id { get; set; }
        public Nullable<int> estado { get; set; }
        public string usuario { get; set; }
        public string salt { get; set; }
        public string clave { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> ultimo_login { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public Nullable<int> pais { get; set; }
        public Nullable<int> provincia { get; set; }
        public Nullable<int> canton { get; set; }
        public Nullable<int> distrito { get; set; }
        public string direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Roles> User_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Companias> Usuarios_Companias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios_Login> Usuarios_Logins { get; set; }
    }
}
