//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Logins
    {
        public int login_id { get; set; }
        public int usuario { get; set; }
        public string nombre { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
